spring:
  application:
    name: service-support
  datasource:
    url: jdbc:mysql://localhost:3306/service_support?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    max-wait: 10000
    max-active: 50
  jpa:
    show_sql : true
    properties:
      hibernate.hbm2ddl.auto: update
      hibernate.sql.show: ture
      hibernate.format_sql : true